FROM python:3.10-alpine

ENV PYTHONUNBUFFERED 1

## Install dependencies
RUN apk add --update --no-cache postgresql-client jpeg-dev
RUN apk add --update --no-cache --virtual .tmp-build-deps \
    gcc libc-dev linux-headers postgresql-dev musl-dev zlib zlib-dev

WORKDIR /app/backend

ADD ./requirements.txt requirements.txt
RUN pip install -r requirements.txt --no-cache-dir

EXPOSE 8000