# Generated by Django 4.1.2 on 2022-10-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='body',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
